#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$app = new Symfony\Component\Console\Application('ferdoc, a Docker helper for PHP');

// ferdoc docker init
$app->add(new Deferdie\Docker\Console\DockerInit);

// ferdoc run
$app->add(new Deferdie\Docker\Console\RunContainers);

// ferdoc stop
$app->add(new Deferdie\Docker\Console\StopContainers);

// ferdoc composer install
$app->add(new Deferdie\Docker\Console\ComposerInstall);

// ferdoc NPM install
$app->add(new Deferdie\Docker\Console\NPMInstall);

// ferdoc NPM watch
$app->add(new Deferdie\Docker\Console\NPMWatch);

// ferdoc test
$app->add(new Deferdie\Docker\Console\TestPhpUnit);

// ferdoc artisan
$app->add(new Deferdie\Docker\Console\Artisan);

$app->run();