#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('ferdoc, a Docker helper for PHP');

// ferdoc docker init
$app->add(new Deferdie\Docker\Console\Commands\DockerInit);

// ferdoc run
$app->add(new Deferdie\Docker\Console\Commands\RunContainers);

// ferdoc stop
$app->add(new Deferdie\Docker\Console\Commands\StopContainers);

// ferdoc build
$app->add(new Deferdie\Docker\Console\Commands\BuildContainers);

// ferdoc composer install
$app->add(new Deferdie\Docker\Console\Commands\ComposerInstall);

// ferdoc NPM
$app->add(new Deferdie\Docker\Console\Commands\NPM);

// ferdoc test
$app->add(new Deferdie\Docker\Console\Commands\TestPhpUnit);

// ferdoc artisan
$app->add(new Deferdie\Docker\Console\Commands\Artisan);

// ferdoc proxy
$app->add(new Deferdie\Docker\Console\ReverseProxy\ReverseProxyCommand);

$app->run();
