#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Process\Process;
use Symfony\Component\Process\Exception\ProcessFailedException;

require('vendor/autoload.php');

$app = new Application('ferdoc');

$app->register('composer install')
    ->addArgument('name')
    ->setCode(function(InputInterface $input, OutputInterface $output){
        $process = new Process('docker-compose run --rm -w /var/www/html app composer install');
        
        $output->writeln('Running composer install, please wait');

        $process->setTimeout(400);

        $process->run(function ($type, $buffer) {
            if (Process::ERR === $type) {
                echo 'ERR > '.$buffer;
            } else {
                echo 'OUT > '.$buffer;
            }
        });

        $output->writeln($process->getOutput());
});

$app->register('npm install')
    ->addArgument('name')
    ->setCode(function(InputInterface $input, OutputInterface $output){
        $process = new Process('docker-compose run --rm -w /var/www/html node npm install');

        $output->writeln('Running NPM install, please wait');

        $process->setTimeout(400);

        $process->run(function ($type, $buffer) {
            if (Process::ERR === $type) {
                echo 'ERR > '.$buffer;
            } else {
                echo 'OUT > '.$buffer;
            }
        });

        $output->writeln($process->getOutput());
});

$app->run();
